<?php

namespace AppBundle\Repository;

/**
 * TickesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends \Doctrine\ORM\EntityRepository
{
}